// Run with: node scripts/seed.js
// Set your env vars first or put them here temporarily

const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

const DESIGNER_BRANDS = ['Burberry','Bvlgari','Carolina Herrera','Chanel','Chopard',
  'Dior','Dries Van Notten','Emporio Armani','Hugo Boss','Issey Miyake',
  'Jean Paul Gaultier','Kenzo','Prada','Tom Ford','Valentino','Versace',
  'Yves Saint Laurent','Guerlain'];

const DUPES_RAW = [
  ['Lattafa','Asad Elixir','Amber · Saffron · Patchouli',179,320],
  ['Lattafa','Asad Bourbon','Bourbon · Vanilla · Tonka',179,320],
  ['Lattafa','Khamrah Dukhan','Smoky · Oud · Sweet',239,370],
  ['Lattafa','Khamrah Qawha','Coffee · Cardamom · Amber',239,370],
  ['Lattafa','Jasoor','Citrus · Woody · Musk',229,340],
  ['Lattafa','Musamam Black Intense','Oud · Saffron · Leather',399,550],
  ['Lattafa','Art of Universe','Spicy · Woody · Amber',299,440],
  ['Riffs','Freeze','Mint · Citrus · Amber',259,400],
  ['French Avenue','Platine Blanc','Fresh · Woody · Clean',349,510],
  ['French Avenue','Magnetiq','Spicy · Oriental · Warm',349,510],
  ['French Avenue','Sun kissed','Citrus · Floral · Bright',349,510],
  ['French Avenue','Forbidden Fruit','Fruity · Sweet · Floral',349,510],
  ['French Avenue','Carnal Desire','Musky · Sensual · Warm',349,510],
  ['French Avenue','Frostbite','Mint · Aquatic · White Musk',349,510],
  ['French Avenue','Teas me','Tea · Citrus · Woody',349,510],
  ['French Avenue','Altantis Extrait','Fresh · Marine · Amber',269,410],
  ['French Avenue','Aether Extrait','Airy · Ozonic · Musk',269,410],
  ['French Avenue','Amber Empire','Amber · Vanilla · Sandalwood',279,420],
  ['French Avenue','Ghost Spectre','Smoky · Woody · Dark',279,440],
  ['French Avenue','Liquid Brun','Cinnamon · Bourbon Vanilla · Praline',0,350],
  ['French Avenue','Royal Blend Sequoia','Raspberry · Cognac · Rose · Sandalwood',0,380],
  ['Rayhaan','Pacific Aura','Aquatic · Citrus · Fresh',199,340],
  ['Rayhaan','Aquatica','Marine · Cool · Woody',209,360],
  ['Rayhaan','Valhalla','Leather · Smoky · Bold',199,340],
  ['Rayhaan','Terra','Earthy · Vetiver · Woody',209,360],
  ['Rayhaan','Obsidian','Dark · Oud · Smoky',209,360],
  ['Rayhaan','Lion','Spicy · Citrus · Woods',199,340],
  ['Rasasi','Hawas Ice','Bergamot · Aquatic · Amber',379,530],
  ['Rasasi','Hawas Fire','Spicy · Warm · Woody',269,410],
  ['Rasasi','Hawas Black','Dark · Smoky · Oriental',269,410],
  ['Rasasi','Hawas Kobra','Bold · Musky · Intense',269,410],
  ['Afnan','9pm Night Out','Dragon Fruit · Cognac · Suede',269,410],
  ['Afnan','9pm Elixir','Sweet · Amber · Spicy',219,360],
  ['Afnan','9pm Rebel','Smoky · Leather · Bold',219,360],
  ['Afnan','Turathi Blue','Aquatic · Citrus · Clean',229,370],
  ['Afnan','Turathi Electric','Fresh · Ozonic · Vibrant',229,370],
  ['Afnan','Supremacy CE','Pineapple · Birch · Oakmoss',279,480],
  ['Afnan','Supremacy NOI','Black Currant · Smoky · Woody',209,370],
  ['Afnan','Lynked Freedom','Fresh · Green · Ozonic',269,420],
  ['Armaf','Odyssey Spectre','Leather · Smoky · Woody',159,270],
  ['Armaf','CDNIM Limited Edition','Pineapple · Birch · Smoky',239,380],
  ['Armaf','Dunescape','Desert · Warm · Sandy',229,370],
  ['Armaf','Cristian Provenzano III','Tangerine · Bergamot · Cedarwood · Musk',560,1060],
  ['Ahmed Al Maghribi','Kaaf','Oud · Rose · Amber',179,310],
  ['Khadlaj','Island','Tropical · Coconut · Musk',149,270],
  ['Khadlaj','Island Dreams','Coconut · Vanilla · Tiare',159,300],
  ['Khadlaj','Shiyaka Snow','Bergamot · Pink Pepper · Vetiver',179,320],
  ['Zimaya','Mazaaj Rhythmn','Rhythmic · Spicy · Warm',179,320],
  ['Arabiyat Prestige','Marwa','Fresh Floral · Citrus · Light Musk',259,390],
  ['Swiss Arabian','Enigma Of Taif','Rose Taif · Oud · Amber',279,530],
  ['Swiss Arabian','Incense 01','Frankincense · Oud · Sandalwood',479,880],
  ['Lattafa','Fahkar Platin','Bergamot · Guava · Sandalwood · Incense',210,370],
  ['Riffs','Fareed','Cardamom · Lavender · Tonka',210,360],
  ['Arabiyat Prestige','Hamdan The Sheikh','Rose · Oud · Leather',280,540],
  ['Nusuk','Ateeq','Oud · Saffron · Musk',200,390],
  ['Lattafa','Dynasty','Floral · Musky · Warm',180,330],
  ['Arabiyat Prestige','Ramad Oriental','Oud · Smoke · Amber',210,400],
  ['Nusuk','Sama','Fresh · Floral · Clean',150,290],
  ['Arabiyat Prestige','Al Noor','Floral · Musk · Fresh',220,420],
  ['Arabiyat Prestige','Mahad Al Dhahab','Oud · Amber · Rose',220,420],
  ['Rayhaan','Jungle Vibe','Green · Tropical · Musk',180,330],
];

const NICHE_RAW = [
  ['Amoroud','Lunar Vetiver Parfum','Vetiver · Iris · Musk',1299,2440],
  ['Amouage','Reflection Man EDP','Neroli · Sandalwood · Musk',1599,2970],
  ['Amouage','Outlands Essence De Parfum','Leather · Smoke · Oud',2199,4130],
  ['Amouage','Memoir Man EDP','Wormwood · Pepper · Leather',1599,2970],
  ['Amouage','Boundless EDP','Citrus · Spice · Woody',1599,2970],
  ['Amouage','Journey Man EDP','Cardamom · Frankincense · Amber',1599,2970],
  ['Amouage','Reflection 45 Man Extrait','Neroli · Cedar · White Musk',1999,3810],
  ['Amouage','Interlude 53 Man Extrait','Frankincense · Oud · Smoky',2199,4130],
  ['Amouage','Search EDP','Rose · Oud · Amber',1599,2970],
  ['Amouage','Lyric Man EDP','Rose · Sandalwood · Musk',1599,2970],
  ['Amouage','Interlude Man EDP','Frankincense · Smoky · Leather',1599,2970],
  ['Amouroud','Wet Stone Parfum','Petrichor · Mineral · Cedar',1599,2970],
  ['Argos','Fall Of Phaeton EDP','Citrus · Floral · Warm',1799,3280],
  ['Argos','Adonis Awakens EDP','Green · Floral · Fresh',1699,3070],
  ['Argos','Triumph of Bacchus EDP','Wine · Spice · Amber',1699,3070],
  ['Argos','Forever Wanted Elixir Parfum','Floral · Musk · Amber',480,910],
  ['Atelier des Ors','Lune Feline Limited Edition 2025','Iris · Musk · Woody',1399,2650],
  ['BDK Parfums','Vanille Leather EDP','Vanilla · Leather · Tobacco',1499,2750],
  ['BDK Parfums','Gris Charnel Extrait','Iris · Sandalwood · Musk',1599,2970],
  ['Burberry','Hero Intense Parfum','Juniper · Cedar · Vetiver',899,1690],
  ['Bvlgari','Tygar EDP','Tiger Lily · Amber · Musk',1799,3280],
  ['Byredo','Mojave Ghost Absolu','Ambrette · Sandalwood · Musk',749,1590],
  ['Carolina Herrera','Bad Boy Extreme EDP','Lemon · Pepper · Tonka',899,1690],
  ['Chanel','Allure Homme Sport Eau Extreme EDP','Pepper · Cedar · Tonka',1399,2540],
  ['Chanel',"Bleu De Chanel L'Exclusif Parfum",'Citrus · Labdanum · Sandalwood',1899,3920],
  ['Chanel','Bleu De Chanel Parfum','Citrus · Woody · Aromatic',1599,2970],
  ['Chopard','Oud Malaki EDP','Oud · Rose · Amber',849,1590],
  ['Clive Christian','1872 Masculine EDP','Bergamot · Lime · Musk · Sandalwood',2240,4420],
  ['Clive Christian','Burlington 1819 EDP','Bergamot · Iris · Sandalwood · Musk',1610,3180],
  ['Creed','Millesime Imperial EDP','Iris · Sea Notes · Musk',1599,2970],
  ['Creed','Original Vetiver EDP','Vetiver · Grapefruit · Pepper',1599,2970],
  ['Creed','Green Irish Tweed EDP','Lemon · Iris · Sandalwood',1799,3280],
  ['Creed','Silver Mountain Water EDP','Tea · Bergamot · Musk',1799,3280],
  ['Creed','Absolu Aventus EDP','Pineapple · Birch · Musk',2799,5400],
  ['Creed','Aventus EDP','Pineapple · Birch · Oakmoss',2399,4660],
  ['Davidoff','Cool Water Man EDT','Mint · Aquatic · Musk',250,450],
  ['Dior','Sauvage EDP','Pepper · Ambroxan · Vanilla',1099,2120],
  ['Dior','Sauvage Elixir','Nutmeg · Sandalwood · Amber',1399,2650],
  ['Diptyque','Tam Dao EDP','Sandalwood · Cypress · Cedar',1590,3130],
  ['Dolce & Gabbana','Light Blue Eau Intense EDP','Grapefruit · Apple · Amber · Musk',710,1360],
  ['Dries Van Notten','Santal Greenery EDP','Sandalwood · Green · Earthy',1599,2970],
  ['Dunhill','Icon EDP','Bergamot · Cardamom · Leather · Amber',340,630],
  ['Emporio Armani','Stronger With You Spices','Cardamom · Vanilla · Chestnut',749,0],
  ['Emporio Armani','Stronger With You Sandalwood EDP','Sandalwood · Vanilla · Warm',1099,2120],
  ['Escentric Molecules','Escentric 01 EDT','Iso E Super · Grapefruit · Pepper',950,1840],
  ["Etat Libre d'Orange",'You Or Someone Like You EDP','Tea · Iris · Woody',999,1910],
  ['Ex Nihilo','Blue Talisman EDP','Mint · Amber · Musk',1699,3070],
  ['Ex Nihilo','Fleur Narcotique EDP','Peach · Rose · Musk · Ambroxan',1450,2850],
  ['Fendi','Mefisto Gentiluomo EDP','Bergamot · Pepper · Vetiver',1220,2380],
  ['Francesca Bianchi','Etruscan Water Extrait','Green · Earthy · Mineral',1899,3500],
  ['Francesca Bianchi','The Dark Side Extrait','Leather · Smoke · Dark',1899,0],
  ['Francesca Bianchi','Sex And The Sea Extrait','Marine · Musky · Sensual',1899,0],
  ['Francesca Bianchi','Libertine Neroli Extrait','Neroli · Citrus · Musk',1599,2970],
  ['Frederic Malle','Musc Ravageur EDP','Vanilla · Amber · Musk',1599,2970],
  ['Frederic Malle','Portrait of a Lady EDP','Rose · Patchouli · Musk',1799,3280],
  ['Giorgio Armani','Acqua Di Gio Profondo Parfum','Aquatic · Mineral · Musk',750,1440],
  ['Giardini di Toscana','Bianco Latte EDP','Milk · Vanilla · Soft Musk',1199,2330],
  ['Goldfield & Banks','Sunset Hour EDP','Coconut · Amber · Warm',1199,2330],
  ['Goldfield & Banks','Pacific Rock Moss EDP','Moss · Vetiver · Citrus',999,1910],
  ['Guerlain',"L'Homme Ideal Parfum",'Almond · Tonka · Leather',999,1910],
  ['Guerlain',"L'Homme Ideal Extreme EDP",'Almond · Tonka · Musk',999,1910],
  ['Guerlain','Tobacco Honey EDP','Tobacco · Honey · Amber',1599,2970],
  ['Guerlain','Cuir Beluga EDP','Leather · Vanilla · Sandalwood',1799,3390],
  ['House of Sillage','Le Sillage Blanc EDP','Bergamot · Rose · Sandalwood',1190,2320],
  ['Hubigaunt','Cologne Intense EDP','Citrus · Aromatic · Musk',999,1910],
  ['Hugo Boss','Boss Bottled Parfum','Apple · Cinnamon · Vetiver',749,1480],
  ['Initio','Rehab Extrait De Parfum','Coffee · Tobacco · Musk',1399,2650],
  ['Initio','Oud for Greatness EDP','Oud · Musk · Incense',1599,2970],
  ['Initio','Absolute Aphrodisiac EDP','Vanilla · Musk · Sensual',1599,2970],
  ['Initio','Musk Therapy Extrait De Parfum','White Musk · Skin · Warm',1599,2970],
  ['Initio','Side Effect EDP','Rum · Tobacco · Vanilla',1599,2970],
  ['Initio','Speed Legends EDP','Citrus · Leather · Woody',1099,0],
  ['Initio','Novae Vanilla EDP','Vanilla · Musk · Sandalwood',870,1680],
  ['Initio','Paragon Extrait De Parfum','Musk · Amber · Sandalwood',950,1860],
  ['Issey Miyake',"L'Eau D'Issey Pour Homme EDP",'Yuzu · Nutmeg · Vetiver',899,1690],
  ['Jean Paul Gaultier','Le Male EDT','Lavender · Vanilla · Mint',749,0],
  ['Jean Paul Gaultier','Le Beau Le Parfum EDP Intense','Coconut · Amber · Vetiver',899,1690],
  ['Jean Paul Gaultier','Scandal Pour Homme Absolu','Ginger · Tonka · Vetiver',800,1550],
  ['Juliette Has a Gun','Not A Perfume EDP','Ambroxan',650,1250],
  ['Jus Et Mad','Aqua Sextius Extrait De Parfum','Mineral · Iris · Amber',1899,3500],
  ['Jusbox','Narcotic Delight EDP','Bergamot · Rose · Benzoin · Musk',1290,2530],
  ['Kajal','Ambassador Man Intense EDP','Bergamot · Iris · Amber · Musk',820,1580],
  ["Kajal","Can't Get Enough EDP",'Iris · Rose · Vanilla · Musk',1340,2620],
  ['Kenzo','Homme Santal Marin EDT','Sandalwood · Marine · Fresh',749,1480],
  ['Kilian','Apple Brandy On The Rocks EDP','Apple · Brandy · Vanilla',1799,3280],
  ["Kilian","Angel's Share On The Rocks EDP",'Cognac · Oak · Vanilla',1899,0],
  ["Kilian","Angels' Share EDP",'Cognac · Cinnamon · Tonka',1799,3280],
  ['Kilian','A Midsummer Dream EDP','Lavender · Vetiver · Musk',1520,2990],
  ['Kilian','Town & Country EDP','Citrus · Vetiver · Musk',2870,5690],
  ['Lorenzo Pazzaglia','Van Py Rhum Extrait','Rum · Vanilla · Woody',1799,3280],
  ['Lorenzo Pazzaglia','Black Sea Extrait','Aquatic · Dark · Amber',1899,3500],
  ['Louis Vuitton','Ombre Nomade EDP','Oud · Leather · Incense',2299,4450],
  ['M.Micallef','Gntonic EDP','Gin · Tonic · Citrus',1099,2120],
  ['Maison Crivelli','Oud Stallion Extrait De Parfum','Oud · Leather · Smoky',2299,4240],
  ['Maison Crivelli','Safran Secret Extrait','Saffron · Rose · Amber',2299,0],
  ['Maison Crivelli','Hibiscus Mahajad Extrait','Hibiscus · Floral · Fruity',1899,0],
  ['Maison Crivelli','Oud Maracuja Extrait','Oud · Passion Fruit · Amber',2299,4450],
  ['Maison Margiela','By The Fireplace EDT','Smoke · Chestnut · Vanilla',999,1910],
  ['Mancera','Red Tobacco EDP','Tobacco · Rose · Amber',749,1480],
  ['Mancera','Aoud Exclusif EDP','Oud · Rose · Musk',650,1250],
  ['Mancera','Cedrat Boise EDP','Grapefruit · Cedar · Musk · Leather',340,630],
  ['Marc Antonnie Barrois','Tilia EDP','Linden · Honey · Woody',1399,2650],
  ['Marc-Antoine Barrois','Ganymede EDP','Suede · Woody · Mineral',1499,2750],
  ['Matiere Premiere','Vanilla Powder EDP','Vanilla · Iris · Powder',1499,2750],
  ['Matiere Premiere','Falcon Leather Extrait','Leather · Smoky · Vetiver',1899,3500],
  ['MDCI Parfums','Chypre Palatin EDP','Chypre · Rose · Oakmoss',1799,3280],
  ['MDCI Parfums','Invasion Barbare EDP','Leather · Tobacco · Smoky',1799,3280],
  ['Memo Paris','Odeon EDP','Iris · Woody · Musk',1099,2120],
  ['Memo Paris','Atomic Rose EDP','Rose · Musk · Cedarwood',1430,2800],
  ['Memo Paris','African Leather EDP','Leather · Spices · Amber',1030,2000],
  ['Mind Games','Blockade Extrait De Parfum','Amber · Oud · Leather',1899,3500],
  ['Mizensir','Perfect Oud Extrait','Oud · Rose · Sandalwood',1699,3070],
  ['Montale','Arabians Tonka EDP','Tonka · Sandalwood · Musk · Amber',260,460],
  ['Nasomatto','Black Afgano Extrait','Cannabis · Oud · Resin',2090,4140],
  ['Nishane','Akdeniz Extrait De Parfum','Citrus · Marine · Amber',1899,0],
  ['Nishane','Ani','Iris · Rose · Sandalwood · Musk',870,1680],
  ['Nishane','Hacivat','Bergamot · Iris · Sandalwood · Ambergris',1350,2640],
  ['Oman Luxury','Royal Incense EDP','Frankincense · Amber · Oud',1499,2750],
  ['Oman Luxury','Caden EDP','Oud · Leather · Musk',1899,3500],
  ['Omanluxury','Khanjar EDP','Oud · Saffron · Amber',1699,3070],
  ['Ormonde Jayne','Nawab Of Oudh Intensivo Extrait','Oud · Rose · Saffron',1899,3500],
  ['Ormonde Jayne','Montabaco Intensivo Parfum','Tobacco · Cedar · Musk',1699,3070],
  ['Orto Parisi','Bergamask Parfum','Bergamot · Musk · Earthy',1899,3500],
  ['Paco Rabanne','Invictus Parfum','Grapefruit · Guaiac Wood · Musk',690,1340],
  ['Pantheon Roma','Annone Extrait De Parfum','Iris · Woody · Leather',1399,2650],
  ['Parfums de Marly','Herod EDP','Tobacco · Vanilla · Pepper',1399,2650],
  ['Parfums de Marly','Layton EDP','Apple · Vanilla · Musk',1399,2650],
  ['Parfums de Marly','Haltane EDP','Juniper · Vetiver · Leather',1499,2750],
  ['Parfums de Marly','Percival EDP','Bergamot · White Flowers · Musk',1299,2440],
  ['Parfums de Marly','Sedley EDP','Mint · Aquatic · Woody',1299,2440],
  ['Parfums de Marly','Althair EDP','Citrus · Aromatic · Amber',1399,2650],
  ['Parfums de Marly','Greenley EDP','Green · Fresh · Earthy',1299,2440],
  ["Penhaligon's",'Halfeti EDP','Rose · Oud · Leather',1599,2970],
  ['Prada',"L'Homme EDT",'Iris · Amber · Vetiver',749,1480],
  ['Prada','Luna Rossa Ocean EDP','Bergamot · Metallic Notes · Amber',650,1250],
  ['Ramon Monegal','Flamenco Extrait De Parfum','Rose · Woody · Spicy',1899,3500],
  ['Roja Parfums','Elysium Pour Homme Parfum','Grapefruit · Neroli · Sandalwood · Musk',2180,4310],
  ['Rosendo Mateu','RM No.5 EDP','Rose · Oud · Amber',1499,2750],
  ['Scentologia','Oud Zarian EDP','Oud · Saffron · Leather',1999,3810],
  ['Scentologia','Oud Voyager EDP','Oud · Incense · Amber',1799,3280],
  ['Serge Lutens',"L'orpheline EDP",'Incense · Musk · Earthy',999,1910],
  ['Serge Lutens','Ambre Sultan EDP','Amber · Resins · Vanilla',1099,2120],
  ['Serge Lutens','Un Bois Vanille EDP','Vanilla · Sandalwood · Warm',999,1910],
  ['Sospiro','Basso EDP','Leather · Tobacco · Dark',1599,2970],
  ['Sospiro','Il Padrino EDP','Tobacco · Amber · Musk',1799,3280],
  ['Sospiro','Vibrato EDP','Citrus · Floral · Woody · Musk',1090,2130],
  ['Thameen','Carved Oud Extrait','Oud · Amber · Smoky',1899,3500],
  ['The Spirit of Dubai','Bahar EDP','Citrus · Green · Woody',1999,3810],
  ['Tom Ford','Grey Vetiver EDP','Vetiver · Grapefruit · Sage',1299,2440],
  ['Tom Ford','Beau De Jour EDP','Lavender · Oakmoss · Musk',1399,2650],
  ['Tom Ford','Black Orchid EDP','Black Orchid · Patchouli · Dark',1099,2120],
  ['Tom Ford','Black Orchid Parfum','Dark · Floral · Woody',1399,2650],
  ['Tom Ford','Tobacco Vanille EDP','Tobacco · Vanilla · Spice',1599,2970],
  ['Tom Ford','Ombre Leather EDP','Leather · Floral · Amber',1030,2000],
  ['Valentino','Uomo Born In Roma Green Stravaganza EDT','Citrus · Green · Fresh',749,0],
  ['Valentino','Uomo Born In Roma Extradose Parfum','Iris · Amber · Warm',899,1690],
  ['Valentino','Uomo Born In Roma Intense EDP','Vanilla · Amber · Intense',849,1590],
  ['Valentino','Donna Born In Roma Intense EDP','Rose · Vanilla · Woody',899,1690],
  ['Versace','Eros Flame EDP','Orange · Pepper · Vanilla',749,1480],
  ['Versace','Eros EDP','Mint · Apple · Vanilla',749,1480],
  ['Viktor & Rolf','Spicebomb Metallic Musk EDP','Musk · Metallic · Amber',610,1170],
  ['Viktor & Rolf','Spicebomb Extreme EDP','Tobacco · Vanilla · Pepper',670,1290],
  ['Vilhelm','Drunk Lovers EDP','Rose · Raspberry · Patchouli · Musk',1470,2880],
  ['Vilhelm','Jump Up And Kiss Me Hedonistic','Patchouli · Rose · Vanilla · Musk',3520,6990],
  ['Vilhelm','Blonde Amber EDP','Amber · Vanilla · Musk · Sandalwood',3590,7130],
  ['Xerjoff','Renaissance EDP','Citrus · Floral · Woody',1299,2540],
  ['Xerjoff','Alexandria II Parfum','Rose · Oud · Amber',1999,3810],
  ['Xerjoff','40 Knots EDP','Marine · Cedar · Musk',1499,2750],
  ['Xerjoff','Torino 24 EDP','Iris · Musk · Woody',1899,3500],
  ['Xerjoff','Torino 21 EDP','Iris · Musk · Woody · Warm',960,1870],
  ['Xerjoff','Tony Iommi Deified Parfum','Rock · Leather · Amber',2299,4450],
  ['Xerjoff','Tony Iommi Monkey Special','Rock · Leather · Amber · Dark',1160,2270],
  ['Xerjoff','Naxos EDP','Lavender · Honey · Tobacco · Vanilla',1299,2540],
  ['Xerjoff','Aldebaran EDP','Bergamot · Iris · Sandalwood · Musk',1330,2610],
  ['Xerjoff','Erba Gold EDP','Bergamot · Iris · Sandalwood',1240,2430],
  ['Xerjoff','Knight of Love EDP','Rose · Oud · Amber · Musk',2420,4790],
  ['Xerjoff','Guidance EDP','Bergamot · Iris · Sandalwood · Musk',1880,3710],
  ['Xerjoff','Aqua Sexitus Extrait','Aquatic · Citrus · Musk · Ambergris',1470,2900],
  ['Yves Saint Laurent','Myslf Le Parfum','Citrus · Woody · Aromatic',1099,2120],
  ["Yves Saint Laurent","Y L'Elixir",'Sage · Tonka · Musk',999,0],
  ['Calvin Klein','Eternity Air EDP','Bergamot · Violet · Sandalwood · Musk',230,410],
  ['Lattafa','Atlas EDP','Oud · Rose · Sandalwood · Amber',270,480],
  ['Ahmed Al Maghribi','Kaaf EDP','Cardamom · Rose · Oud · Musk',260,460],
  ['Arabiyat Prestige','Marwa EDP','Floral · Rose · Musk · Sandalwood',300,550],
  ['Bulgari','Le Gemme Tygar EDP','Oud · Amber · Incense · Musk',1970,3890],
  ['Elie Saab','Power Of You Pour Femme EDP','Rose · Jasmine · Musk',2440,4820],
];

const PRODUCT_IMAGES = {
  'Xerjoff|Naxos EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777110450/Perfumes/Xerjoff/Xerjoff_Naxos_e5jnbx.jpg',
  'Creed|Silver Mountain Water EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447502/IMG_0755_gauhos.jpg',
  'Xerjoff|40 Knots EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447502/IMG_0756_uxlwdq.jpg',
  'Goldfield & Banks|Sunset Hour EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447502/IMG_0789_f08z09.jpg',
  'Xerjoff|Tony Iommi Deified Parfum': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447502/IMG_0762_aie0qa.jpg',
  'Initio|Side Effect EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447502/IMG_0758_kfpwwm.jpg',
  'Jus Et Mad|Aqua Sextius Extrait De Parfum': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447502/IMG_0761_womwho.jpg',
  'Parfums de Marly|Layton EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447501/IMG_0759_dwvxx7.jpg',
  'Initio|Musk Therapy Extrait De Parfum': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447502/IMG_0757_qh71ie.jpg',
  'Matiere Premiere|Falcon Leather Extrait': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447501/IMG_0792_x8ebsk.jpg',
  'Argos|Adonis Awakens EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447501/IMG_0783_gdh88d.jpg',
  'Argos|Triumph of Bacchus EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447501/IMG_0785_akmobo.jpg',
  'Xerjoff|Torino 24 EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447501/IMG_0786_cxxd5s.jpg',
  'Orto Parisi|Bergamask Parfum': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447501/IMG_0787_ygzctn.jpg',
  'Amouage|Reflection 45 Man Extrait': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447501/IMG_0791_hhcrpx.jpg',
  'Creed|Green Irish Tweed EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447500/IMG_0790_nq1g4d.jpg',
  'Oman Luxury|Caden EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447500/IMG_0698_xoh8be.jpg',
  "Kilian|Angels' Share EDP": 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447500/IMG_0794_rhnz6u.jpg',
  'Matiere Premiere|Vanilla Powder EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447500/IMG_0799_n5gepb.jpg',
  'Mizensir|Perfect Oud Extrait': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447500/IMG_0801_pikxh3.jpg',
  'Parfums de Marly|Greenley EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447500/IMG_0750_bkkt9o.jpg',
  'Maison Crivelli|Oud Stallion Extrait De Parfum': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447500/IMG_0793_alvic7.jpg',
  'Creed|Millesime Imperial EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447500/IMG_0798_lwfo29.jpg',
  'Thameen|Carved Oud Extrait': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447497/IMG_0803_czcx9j.jpg',
  'Parfums de Marly|Herod EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447498/IMG_0752_kjqjqw.jpg',
  'Amouage|Search EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447498/IMG_0804_qcpahs.jpg',
  'Scentologia|Oud Zarian EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447497/IMG_0754_j8kw1n.jpg',
  'Xerjoff|Alexandria II Parfum': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447499/IMG_0760_b7swew.jpg',
  'Frederic Malle|Portrait of a Lady EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447499/IMG_0800_igt3iz.jpg',
  'Omanluxury|Khanjar EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447499/IMG_0749_zmzsky.jpg',
  "Serge Lutens|L'orpheline EDP": 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447499/IMG_0796_g6hggn.jpg',
  'Creed|Original Vetiver EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447499/IMG_0797_bkvruj.jpg',
  'Nishane|Ani': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447498/IMG_0802_w8g4us.jpg',
  'Nishane|Hacivat': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447497/IMG_0805_ybnn5j.jpg',
  'Xerjoff|Tony Iommi Monkey Special': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447499/IMG_0751_vfo1px.jpg',
  'Sospiro|Vibrato EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447499/IMG_0748_u6xrw7.jpg',
  'Xerjoff|Torino 21 EDP': 'https://res.cloudinary.com/dlakipgdf/image/upload/v1777447499/IMG_0753_tsjpyf.jpg',
};

async function seed() {
  console.log('Seeding products...');
  const products = [];

  for (const [brand, name, notes, p5, p10] of DUPES_RAW) {
    const p20 = p10 > 0 ? Math.round((p10 * 1.8) / 10) * 10 : 0;
    const imgKey = `${brand}|${name}`;
    products.push({
      brand, name, notes,
      category: 'dupe',
      p5, p10, p20,
      image_url: PRODUCT_IMAGES[imgKey] || null,
      sold_out: false, visible: true,
    });
  }

  for (const [brand, name, notes, p5, p10] of NICHE_RAW) {
    const p20 = p10 > 0 ? Math.round((p10 * 1.8) / 10) * 10 : 0;
    const category = DESIGNER_BRANDS.includes(brand) ? 'designer' : 'niche';
    const imgKey = `${brand}|${name}`;
    products.push({
      brand, name, notes,
      category,
      p5, p10, p20,
      image_url: PRODUCT_IMAGES[imgKey] || null,
      sold_out: false, visible: true,
    });
  }

  const { error } = await supabase.from('products').insert(products);
  if (error) { console.error('Products error:', error); return; }
  console.log(`✓ Inserted ${products.length} products`);

  // Seed partials
  const partials = [
    { brand:'Creed', name:'Absolu Aventus EDP', notes:'Pineapple · Birch · Musk · Oakmoss', full_ml:100, ml_left:30, p5:960, p10:1870, price:13999, condition:'Tester — 30ml remaining', visible:true, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777139524/Perfumes/Partials/IMG_0703_regfol.jpg' },
    { brand:'Mancera', name:'Cedrat Boise EDP', notes:'Grapefruit · Cedar · Musk · Leather', full_ml:100, ml_left:40, p5:340, p10:630, price:4299, condition:'Good condition — 40ml remaining', visible:true, sold_out:true, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137928/Perfumes/Partials/IMG_0712_sayvj4.jpg' },
    { brand:'Jean Paul Gaultier', name:'Le Beau EDT', notes:'Vanilla · Bergamot · Tonka · Iris', full_ml:125, ml_left:40, p5:270, p10:490, price:3999, condition:'Good condition — 40ml remaining', visible:true, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137929/Perfumes/Partials/IMG_0715_k1mwp7.jpg' },
    { brand:'Rasasi', name:'Hawas Black', notes:'Aquatic · Sandalwood · Musk · Amber', full_ml:100, ml_left:10, p5:500, p10:0, price:500, condition:'10ml remaining', visible:true, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137929/Perfumes/Partials/IMG_0723_lfo392.jpg' },
    { brand:'Goldfield & Banks', name:'Pacific Rock Moss EDP', notes:'Bergamot · Ambrette · Rock Moss · Musk', full_ml:100, ml_left:20, p5:310, p10:580, price:3799, condition:'Good condition — 20ml remaining', visible:true, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137927/Perfumes/Partials/IMG_0711_vecuxm.jpg' },
    { brand:'Kenzo', name:'Pour Homme EDP', notes:'Lotus · Sage · Sandalwood · Amber', full_ml:100, ml_left:23, p5:190, p10:330, price:2000, condition:'Good condition — 23ml remaining', visible:true, sold_out:true, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777139950/Perfumes/Partials/IMG_0741_vzswcm.jpg' },
    { brand:'Lattafa', name:'Atlas EDP', notes:'Oud · Rose · Sandalwood · Amber', full_ml:55, ml_left:25, p5:270, p10:480, price:1750, condition:'Good condition — 25ml remaining', visible:true, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137929/Perfumes/Partials/IMG_0719_dljegy.jpg' },
    { brand:'Ahmed Al Maghribi', name:'Kaaf EDP (Partial)', notes:'Cardamom · Rose · Oud · Musk', full_ml:100, ml_left:40, p5:260, p10:460, price:1200, condition:'Good condition — 40ml remaining', visible:true, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137929/Perfumes/Partials/IMG_0721_c9lsxy.jpg' },
    { brand:'Arabiyat Prestige', name:'Marwa EDP', notes:'Floral · Rose · Musk · Sandalwood', full_ml:100, ml_left:45, p5:300, p10:550, price:1650, condition:'Good condition — 45ml remaining', visible:true, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137927/Perfumes/Partials/IMG_0716_gigeh1.jpg' },
    { brand:'Chopard', name:'Oud Malaki EDP', notes:'Oud · Leather · Amber · Musk', full_ml:100, ml_left:30, p5:240, p10:440, price:2800, condition:'Good condition — 30ml remaining', visible:true, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137929/Perfumes/Partials/IMG_0725_c56lg8.jpg' },
    { brand:'Dunhill', name:'Icon EDP', notes:'Bergamot · Cardamom · Leather · Amber', full_ml:100, ml_left:40, p5:340, p10:630, price:4299, condition:'Good condition — 40ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777139814/Perfumes/Partials/IMG_0740_r0rob4.jpg' },
    { brand:'Dior', name:'Sauvage EDP', notes:'Bergamot · Ambroxan · Vanilla', full_ml:200, ml_left:20, p5:180, p10:310, price:3600, condition:'200ml bottle — 20ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137930/Perfumes/Partials/IMG_0735_t2ot04.jpg' },
    { brand:'Afnan', name:'Supremacy Not Only Intense EDP', notes:'Pineapple · Birch · Musk', full_ml:150, ml_left:50, p5:130, p10:210, price:1500, condition:'Good condition — 50ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137930/Perfumes/Partials/IMG_0730_gdsnmd.jpg' },
    { brand:'Montale', name:'Arabians Tonka EDP', notes:'Tonka · Sandalwood · Musk · Amber', full_ml:100, ml_left:35, p5:260, p10:460, price:3000, condition:'Good condition — 35ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137928/Perfumes/Partials/IMG_0710_jp6wtn.jpg' },
    { brand:'Afnan', name:'Turathi Blue EDP', notes:'Aquatic · Musk · Amber · Vetiver', full_ml:90, ml_left:60, p5:210, p10:360, price:1999, condition:'Good condition — 60ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137928/Perfumes/Partials/IMG_0714_sn5c7u.jpg' },
    { brand:'Davidoff', name:'Cool Water EDT', notes:'Mint · Aquatic · Sandalwood · Musk', full_ml:150, ml_left:50, p5:140, p10:240, price:1850, condition:'Good condition — 50ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137929/Perfumes/Partials/IMG_0718_kh4h5o.jpg' },
    { brand:'Versace', name:'Eros EDP', notes:'Mint · Lemon · Tonka · Vanilla · Amber', full_ml:100, ml_left:30, p5:240, p10:440, price:2799, condition:'Tester — 30ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137930/Perfumes/Partials/IMG_0728_vfwhru.jpg' },
    { brand:'Yves Saint Laurent', name:'Y EDP', notes:'Bergamot · Sage · Tonka · Cedar', full_ml:100, ml_left:20, p5:220, p10:380, price:2400, condition:'Good condition — 20ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137930/Perfumes/Partials/IMG_0736_kiafd0.jpg' },
    { brand:'Calvin Klein', name:'Eternity Air EDP', notes:'Bergamot · Violet · Sandalwood · Musk', full_ml:100, ml_left:98, p5:230, p10:410, price:2600, condition:'Tester — 98ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137929/Perfumes/Partials/IMG_0724_bl5i9s.jpg' },
    { brand:'Mancera', name:'Red Tobacco EDP', notes:'Tobacco · Rose · Amber · Oud', full_ml:100, ml_left:30, p5:260, p10:470, price:3100, condition:'Good condition — 30ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137928/Perfumes/Partials/IMG_0709_lmpcw1.jpg' },
    { brand:'Mancera', name:'Aoud Exclusif EDP', notes:'Oud · Rose · Amber · Musk', full_ml:100, ml_left:30, p5:260, p10:460, price:900, condition:'Good condition — 30ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137930/Perfumes/Partials/IMG_0727_l1tvpb.jpg' },
    { brand:'Kenzo', name:'Pour Homme Santal Marin EDP', notes:'Sandalwood · Marine · Cedar · Musk', full_ml:100, ml_left:30, p5:250, p10:440, price:2850, condition:'Good condition — 30ml remaining', visible:false, sold_out:false, image_url:'https://res.cloudinary.com/dlakipgdf/image/upload/v1777137929/Perfumes/Partials/IMG_0720_poxilz.jpg' },
  ];

  const { error: pe } = await supabase.from('partials').insert(partials);
  if (pe) { console.error('Partials error:', pe); return; }
  console.log(`✓ Inserted ${partials.length} partials`);

  console.log('\n✅ Seed complete!');
}

seed();
